imgurl.lo: /root/down/lnmp1.0-full/php-5.3.28/ext/imgurl/imgurl.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/down/lnmp1.0-full/php-5.3.28/ext/imgurl $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/down/lnmp1.0-full/php-5.3.28/ext/imgurl/imgurl.c -o imgurl.lo 
$(phplibdir)/imgurl.la: ./imgurl.la
	$(LIBTOOL) --mode=install cp ./imgurl.la $(phplibdir)

./imgurl.la: $(shared_objects_imgurl) $(IMGURL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_imgurl) $(IMGURL_SHARED_LIBADD)

